Fix clearing all passwords from the clear data dialog
Epiphany saves passwords with EPHY_FORM_PASSWORD_SCHEMA. If we want to
delete the passwords we've saved, we have to pass that schema to
libsecret. Using the SECRET_SCHEMA_COMPAT_NETWORK guarantees we will
only delete passwords saved by other apps, and none of our own
passwords.

Exception: WebKitGTK+ is saving HTTP auth passwords with
SECRET_SCHEMA_COMPAT_NETWORK. This change means those passwords will no
longer be deleted, which is non-ideal.

https://bugzilla.gnome.org/show_bug.cgi?id=755190